require 'pry'
require 'json'
require 'open-uri'
require 'net/http'

require_relative './gardener/cli'
require_relative './gardener/api'
require_relative './gardener/plant'
# require_relative './gardener/instruction'
# require_relative './gardener/description'